name: tour_maker
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  audioplayers: ^3.0.1
  cached_network_image: ^3.2.3
  country_picker: ^2.0.19
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  date_time_picker: ^2.1.0
  device_info_plus: ^8.1.0
  dio: ^5.0.1
  esys_flutter_share_plus: ^2.2.0
  expansion_tile_card: ^2.0.0
  firebase_app_check: ^0.1.1+8
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.0
  firebase_messaging: ^14.2.5
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.0+1
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  get: ^4.6.5
  get_cli: ^1.8.1
  get_storage: ^2.0.3
  google_fonts: ^4.0.3
  http: ^0.13.5
  http_parser: ^4.0.2
  image_picker: ^0.8.6+1
  internet_connection_checker: ^1.0.0+1
  intl: ^0.17.0
  logger: ^1.3.0
  path_provider: ^2.0.13
  pinput: ^2.2.21
  pretty_dio_logger: ^1.1.1
  razorpay_flutter: 1.3.3
  shared_preferences: ^2.1.0
  shimmer: ^2.0.0
  sizer: ^2.0.15
  sms_autofill: ^2.2.0
  syncfusion_flutter_pdfviewer: ^21.1.38
  timer_count_down: ^2.2.2
  url_launcher: ^6.1.9
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/Logo.png
    - assets/tourmakersplash.png
    - assets/Illustration.png
    - assets/Accept illustration.png
    - assets/farshad-rezvanian-Eelegt4hFNc-unsplash.jpg
    - assets/Avatar.png
    - assets/onboarding.png
    - assets/Background.png
    - assets/Logo on.png
    - assets/tourmaker.svg
    - assets/Thumbnail.png
    - assets/camera.svg
    - assets/empty screen.png
    - assets/help.svg
    - assets/feedback.svg
    - assets/about.svg
    - assets/noInternet.png
    - assets/typewriter-1.mp3
    - assets/whatsapp.svg
  fonts:
    - family: TourMaker
      fonts:
        - asset: assets/TourMaker.ttf
    - family: MontserratBold
      fonts:
        - asset: fonts/Montserrat/static/Montserrat-Bold.ttf
    - family: MontserratRegular
      fonts:
        - asset: fonts/Montserrat/static/Montserrat-Regular.ttf
    - family: MontserratSemiBold
      fonts:
        - asset: fonts/Montserrat/static/Montserrat-SemiBold.ttf
    - family: MontserratMedium
      fonts:
        - asset: fonts/Montserrat/static/Montserrat-Medium.ttf
    - family: Tahu
      fonts:
        - asset: fonts/Tahu!.ttf
    - family: Mesa
      fonts:
        - asset: fonts/Mesa Grande.ttf
    - family: TypeWriter
      fonts:
        - asset: fonts/rm_typerighter_old.ttf
